import { ALL_MAIN_TENSES, DEFAULT_IMPERATIVE_PERSONAL, DEFAULT_PERSONAL } from "./Data.js";
const verbs = [{ voc: "abrazar", meaning: "to embrace, hug; to include", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "abrigar", meaning: "to shelter", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "abrir", meaning: "to open", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "absolver", meaning: "to acquit, absolve", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "abstenerse", meaning: "to abstain", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "abstraer", meaning: "to abstract; to remove", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "acentuar", meaning: "to emphasize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "acercar", meaning: "to bring closer", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "acertar", meaning: "to be right; to manage to", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "acordar", meaning: "to agree, decide", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "acostarse", meaning: "to go to bed", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "actualizar", meaning: "to update", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "actuar", meaning: "to act; to activate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "adelgazar", meaning: "to lose weight", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "adherir", meaning: "to adhere; to join", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "advertir", meaning: "to notice, observe; to warn, advise", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "afianzar", meaning: "to reinforce; to guarantee", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "aficionarse", meaning: "to become fond of", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "agradecer", meaning: "to thank, to be thankful for", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "agregar", meaning: "to gather, aggregate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "alcanzar", meaning: "to reach, overtake", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "alentar", meaning: "to encourage", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "almorzar", meaning: "to have lunch", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "alzar", meaning: "to lift, elevate; to remove", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "amanecer", meaning: "to dawn; to wake up", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "amenazar", meaning: "to threaten", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ampliar", meaning: "to enlarge", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "amplificar", meaning: "to amplify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "analizar", meaning: "to analyze", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "andar", meaning: "to walk, go, travel", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "apagar", meaning: "to extinguish, turn off", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "aparcar", meaning: "to park", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "aparecer", meaning: "to appear, show up", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "aplazar", meaning: "to postpone", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "aplicar", meaning: "to apply, assign", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "apostar", meaning: "to bet", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "apretar", meaning: "to tighten; to afflict", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "aprobar", meaning: "to approve; to pass (a class)", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "argüir", meaning: "to argue; to accuse", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "arrancar", meaning: "to uproot, snatch; to start", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "arrendar", meaning: "to rent", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "arrepentirse", meaning: "to repent, regret", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "arriesgar", meaning: "to risk", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ascender", meaning: "to promote; to ascend", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "asentir", meaning: "to assent", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "atacar", meaning: "to attack", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "atender", meaning: "to attend to, heed", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "atenerse", meaning: "to obey; to rely on", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "aterrizar", meaning: "to land, disembark", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "atraer", meaning: "to attract, appeal to", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "atravesar", meaning: "to cross, pass through", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "atreverse", meaning: "to dare", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "atribuir", meaning: "to attribute to", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "autografiar", meaning: "to autograph", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "autorizar", meaning: "to authorize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "avanzar", meaning: "to advance", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "avergonzar", meaning: "to shame", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "averiguar", meaning: "to find out, ascertain", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "bautizar", meaning: "to baptize; to christen", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "bostezar", meaning: "to yawn", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "brincar", meaning: "to jump, skip", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "buscar", meaning: "to look for, search", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "caber", meaning: "to fit", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "caer", meaning: "to fall, collapse", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "calentar", meaning: "to warm, heat", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "calificar", meaning: "to qualify; to assess", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "calzar", meaning: "to wear (shoes)", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "caracterizar", meaning: "to characterize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "carecer", meaning: "to lack", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "cargar", meaning: "to load, burden", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "castigar", meaning: "to punish, castigate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "cazar", meaning: "to hunt; to chase", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ceñir", meaning: "to surround; to shorten", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "cercar", meaning: "to enclose", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "cerrar", meaning: "to close, obstruct", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "certificar", meaning: "to certify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "chocar", meaning: "to shock, startle; to collide with", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "civilizar", meaning: "to civilize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "clarificar", meaning: "to clarify, illuminate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "clasificar", meaning: "to classify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "cocer", meaning: "to cook, bake", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "coger", meaning: "to catch, grasp, gather", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "colegir", meaning: "to gather", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "colgar", meaning: "to hang; to attribute", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "colocar", meaning: "to position, arrange", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "colonizar", meaning: "to colonize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "comenzar", meaning: "to begin, to commence", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "competir", meaning: "to compete", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "complicar", meaning: "to complicate; to involve", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "componer", meaning: "to compose", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "comprobar", meaning: "to verify; to prove", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "comulgar", meaning: "to take communion; to agree", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "comunicar", meaning: "to communicate; to connect", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "concebir", meaning: "to conceive, imagine", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "concernir", meaning: "to concern", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "concertar", meaning: "to coordinate; to agree to", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "concluir", meaning: "to conclude", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "concordar", meaning: "to agree, to reconcile", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "conducir", meaning: "to lead, drive, conduct", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "conferir", meaning: "to confer, give", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "confiar", meaning: "to confice, trust", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "confluir", meaning: "to meet, join", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "conmover", meaning: "to move", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "conocer", meaning: "to know; to meet", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "conseguir", meaning: "to get, obtain, manage", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "consentir", meaning: "to consent; to bear", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "consolar", meaning: "to console", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "constituir", meaning: "to constitute", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "construir", meaning: "to build, construct", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "contar", meaning: "to count; to bear in mind; to tell", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "contener", meaning: "to contain", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "continuar", meaning: "to continue", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "contraer", meaning: "to contract", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "contraponer", meaning: "to compare, counter with", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "contravenir", meaning: "to contravene", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "contribuir", meaning: "to contribute", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "convalecer", meaning: "to convalesce, recover", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "convencer", meaning: "to convince", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "convenir", meaning: "to agree; to suit", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "convertir", meaning: "to convert", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "convocar", meaning: "to convoke, summon", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "corregir", meaning: "to correct; to reprimand, punish", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "costar", meaning: "to cost", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "crecer", meaning: "to grow", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "creer", meaning: "to believe", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "criar", meaning: "to feed; to grow, raise", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "criticar", meaning: "to criticize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "cruzar", meaning: "to cross, intersect", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "cubrir", meaning: "to cover", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "danzar", meaning: "to dance; (inf) to meddle", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "dar (to give)", meaning: "verb tables", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "decender", meaning: "to descend", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "decir (to say, to tell)", meaning: "verb tables", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "dedicar", meaning: "to dedicate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "deducir", meaning: "to deduce; to deduct", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "defender", meaning: "to defend, protect, uphold", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "deferir", meaning: "to defer, delegate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "delegar", meaning: "to delegate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "delinquir", meaning: "to break the law, commit an offense", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "demostrar", meaning: "to show, prove, demonstrate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "denegar", meaning: "to refuse, reject", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "deponer", meaning: "to depose; to put down", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "desafiar", meaning: "to challenge, defy", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "desaparecer", meaning: "to disappear", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "desaprobar", meaning: "to disapprove of; to condemn", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "descalzar", meaning: "to take off shoes; to undermine", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "descender", meaning: "to descend", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "descolgar", meaning: "to take down, unhang", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "desconocer", meaning: "to not know; to disown", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "descubrir", meaning: "to discover", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "desenvolver", meaning: "to unwrap; to unroll", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "deshacer", meaning: "to undo; to destroy", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "deslizar", meaning: "to slide, slip", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "desmentir", meaning: "to deny, believe", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "desobedecer", meaning: "to disobey", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "desorganizar", meaning: "to disorganize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "despedir", meaning: "to say good-bye, dismiss", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "despegar", meaning: "to detach; to take off (airplane)", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "despenalizar", meaning: "to legalize, decriminalize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "despertar", meaning: "to wake up, awaken", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "destrozar", meaning: "to destroy", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "destruir", meaning: "to destroy, ruin, damage", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "desvestir", meaning: "to undress", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "desviar", meaning: "to deviate, deflect", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "detener", meaning: "to detain, stop", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "devenir", meaning: "to become", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "devolver", meaning: "to return; to refund", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "digerir", meaning: "to digest", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "dirigir", meaning: "to direct, address; to manage, run", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "discernir", meaning: "to discern", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "disentir", meaning: "to dissent", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "disfrazar", meaning: "to disguise, conceal", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "disminuir", meaning: "to diminish", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "disolver", meaning: "to dissolve", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "disponer", meaning: "to dipose of; to arrange, order", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "distinguir", meaning: "to distinguish, discern", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "distraer", meaning: "to distract, divert, amuse", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "distribuir", meaning: "to distribute", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "divertir", meaning: "to amuse, entertain, divert", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "divulgar", meaning: "to divulge", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "doler", meaning: "to hurt, ache", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "dormir", meaning: "to sleep", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ducharse", meaning: "to take a shower", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "economizar", meaning: "to save, economize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "edificar", meaning: "to build, edify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "educar", meaning: "to educate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "efectuar", meaning: "to effect", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ejercer", meaning: "to exert", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "elegir", meaning: "to choose, select, elect", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "embarazar", meaning: "to hinder; to make pregnant", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "embarcar", meaning: "to embark", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "empezar", meaning: "to begin, commence", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "enamorarse", meaning: "to fall in love", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "encabezar", meaning: "to lead, head", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "encantarle", meaning: "to enchant, bewitch, delight", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "encender", meaning: "to ignite; to turn on; to provoke", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "encerrar", meaning: "to confine, enclose; to comprise", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "encoger", meaning: "to shrink", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "encomendar", meaning: "to entrust", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "encontrar", meaning: "to meet, find, encounter", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "endulzar", meaning: "to sweeten", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "enfriar", meaning: "to cool", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "engolfarse", meaning: "to get involved", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ennegrecer", meaning: "to blacken, darken", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "entender", meaning: "to understand; to intend, mean", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "entregar", meaning: "to deliver, surrender", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "entretener", meaning: "to entertain, to hold up, delay", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "enviar", meaning: "to send", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "envolver", meaning: "to wrap, pack, enfold", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "equivaler", meaning: "to be equivalent", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "equivocar", meaning: "to mistake, miss", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "erigir", meaning: "to erect, build", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "errar", meaning: "to err, miss; to wander", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "escoger", meaning: "to choose", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "esforzar", meaning: "to strengthen, invigorate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "esparcir", meaning: "to spread, scatter; to amuse, divert", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "especificar", meaning: "to specify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "espiar", meaning: "to spy on", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "esquiar", meaning: "to ski", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "establecer", meaning: "to establish", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "estar (to be)", meaning: "verb tables", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "evacuar", meaning: "to evacuate; to fulfill", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "evocar", meaning: "to evoke, invoke", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "exceptuar", meaning: "to except, exclude, exempt", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "excluir", meaning: "to exclude", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "exigir", meaning: "to demand, require", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "expedir", meaning: "to issue; to ship", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "explicar", meaning: "to explain", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "exponer", meaning: "to expose, display", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "extender", meaning: "to extend; to draw up", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "extinguir", meaning: "to extinguish, exterminate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "extraer", meaning: "to extract", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "fabricar", meaning: "to manufacture, fabricate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "falsificar", meaning: "to falsify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "faltarle", meaning: "to lack, be lacking", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "familiarizar", meaning: "to familiarize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "fatigar", meaning: "to fatigue", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "favorecer", meaning: "to favor; to flatter", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "fiar", meaning: "to entrust; to guarantee", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "fijarse", meaning: "to pay attention, notice", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "finalizar", meaning: "to finish", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "fingir", meaning: "to feign, fake", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "florecer", meaning: "to flower, flourish", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "fluir", meaning: "to flow", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "fornicar", meaning: "to fornicate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "forzar", meaning: "to force", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "fotografiar", meaning: "to photograph", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "fregar", meaning: "to scrub; to wash dishes", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "freír", meaning: "to fry", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "garantizar", meaning: "to guarantee", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "gemir", meaning: "to groan, moan", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "generalizar", meaning: "to generalize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "gobernar", meaning: "to govern", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "gozar", meaning: "to enjoy; to have", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "graduar", meaning: "to grade, classify; to graduate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "gratificar", meaning: "to reward; to gratify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "guiar", meaning: "to guide, lead; to drive", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "gustarle", meaning: "to taste; to like, be pleasing", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "haber (‘have’ in perfect tenses)", meaning: "verb tables", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "habituar", meaning: "to habituate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "hacer (to do, to make)", meaning: "verb tables", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "hallarse", meaning: "to be located", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "heder", meaning: "to stink; to annoy", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "helar", meaning: "to freeze; to astonish", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "henchir", meaning: "to stuff, fill", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "herir", meaning: "to injure, hurt", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "hervir", meaning: "to boil; to seethe", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "holgar", meaning: "to rest; to be superfluous", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "hospitalizar", meaning: "to hospitalize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "huir", meaning: "to flee, escape", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "identificar", meaning: "to identify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "impedir", meaning: "to prevent, impede", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "implicar", meaning: "to implicate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "imponer", meaning: "to impose, demand", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "importarle", meaning: "to matter, be important", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "incluir", meaning: "to include, contain", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "indicar", meaning: "to indicate, point out", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "inducir", meaning: "to persuade, induce", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "inferir", meaning: "to infer", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "influir", meaning: "to influence, have influence", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "insinuar", meaning: "to insinuate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "instituir", meaning: "to institute", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "instruir", meaning: "to instruct", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "interesar", meaning: "to interest, appeal to, concern, involve", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "intervenir", meaning: "to intervene; to supervise", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "introducir", meaning: "to introduce, insert, input", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "invertir", meaning: "to invert; to invest", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "investigar", meaning: "to investigate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "invocar", meaning: "to invoke; to implore", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ir (to go)", meaning: "verb tables", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "jactarse", meaning: "to brag", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "jugar", meaning: "to play", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "justificar", meaning: "to justify; to verify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "juzgar", meaning: "to judge", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "lanzar", meaning: "to throw, launch", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "leer", meaning: "to read", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "legalizar", meaning: "to legalize; to authenticate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "levantarse", meaning: "to get up, get out of bed", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "liar", meaning: "to tie", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ligar", meaning: "to tie; to mix", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "llamarse", meaning: "to call, be named; to draw, attract", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "llegar", meaning: "to arrive, reach", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "llover", meaning: "to rain", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "lubricar", meaning: "to lubricate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "malcriar", meaning: "to spoil, pamper", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "maldecir", meaning: "to curse, swear", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "maltraer", meaning: "to insult, abuse, mistreat", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "mantener", meaning: "to maintain, support", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "maquillarse", meaning: "to put on make-up", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "marcar", meaning: "to mark, notice; indicate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "mascar", meaning: "to chew; (inf) to mumble", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "masticar", meaning: "to chew, masticate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "mecer", meaning: "to rock, swing, sway, stir", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "medir", meaning: "to compare, measure", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "memorizar", meaning: "to memorize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "menguar", meaning: "to diminish; to discredit", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "mentir", meaning: "to lie", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "merecer", meaning: "to deserve, merit", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "mitigar", meaning: "to mitigate, appease", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "modernizar", meaning: "to modernize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "modificar", meaning: "to modify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "moler", meaning: "to grind, wear out", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "morder", meaning: "to bite; to corrode", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "morir", meaning: "to die; to kill", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "mostrar", meaning: "to show, point out", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "mover", meaning: "to move; to cause, provoke", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "multiplicar", meaning: "to multiply", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "nacer", meaning: "to be born; to hatch, sprout", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "naturalizar", meaning: "to naturalize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "navegar", meaning: "to navigate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "negar", meaning: "to deny, reject, refuse", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "nevar", meaning: "to snow", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "normalizar", meaning: "to normalize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "notificar", meaning: "to notify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "obedecer", meaning: "to obey", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "obligar", meaning: "to force, compel, oblige", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "obstruir", meaning: "to obstruct", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "obtener", meaning: "to obtain, get", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ocurrir", meaning: "to occur", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ofrecer", meaning: "to give, offer, present", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ofuscar", meaning: "to obfuscate; to dazzle", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "oír", meaning: "to hear, listen", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "oler", meaning: "to smell; to pry into, sniff out", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ondularse", meaning: "to wave, undulate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "oponer", meaning: "to oppose", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "organizar", meaning: "to organize, set up", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "oscurecer", meaning: "to obscure", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "pagar", meaning: "to pay, repay", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "parecer", meaning: "to seem, appear, look", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "pedir", meaning: "to ask for, request, order", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "pegar", meaning: "to beat, hit; to glue, adhere", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "pensar", meaning: "to think", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "perder", meaning: "to lose", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "perecer", meaning: "to perish", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "perjudicar", meaning: "to harm, prejudice", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "permanecer", meaning: "to stay, remain", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "perseguir", meaning: "to pursue, persecute", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "personalizar", meaning: "to personalize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "personificar", meaning: "to personify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "pertenecer", meaning: "to pertain", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "pervertir", meaning: "to pervert", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "pescar", meaning: "to fish, catch", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "picar", meaning: "to pierce, prick; to sting", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "plagar", meaning: "to plague", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "platicar", meaning: "to talk, chat", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "poder (can, may, to be able)", meaning: "verb tables", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "poner", meaning: "to put; to switch", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "portarse", meaning: "to behave", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "poseer", meaning: "to possess, own", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "posponer", meaning: "to postpone; to place after", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "practicar", meaning: "to practice; to perform, carry out", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "predecir", meaning: "to predict", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "predicar", meaning: "to preach", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "predisponer", meaning: "to predispose, prejudice, bias", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "preferir", meaning: "to prefer", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "preocuparse", meaning: "to worry, preoccupy", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "preponer", meaning: "to place before", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "presentir", meaning: "to have a premonition; to feel, be aware", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "presuponer", meaning: "to presuppose, assume", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "prevalecer", meaning: "to prevail, thrive", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "prevenir", meaning: "to prevent; to warn; to prepare", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "prever", meaning: "to foresee, anticipate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "probar", meaning: "to test, try; to prove", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "producir", meaning: "to produce; to cause", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "proferir", meaning: "to utter", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "promover", meaning: "to promote", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "promulgar", meaning: "to promulgate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "propagar", meaning: "to propogate, disseminate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "proponer", meaning: "to propose, suggest", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "proseguir", meaning: "to continue, proceed with", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "proteger", meaning: "to protect", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "proveer", meaning: "to provide", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "provenir", meaning: "to come from, stem from", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "provocar", meaning: "to provoke; to tempt; to bring about", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "publicar", meaning: "to publish, publicize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "puntuar", meaning: "to punctuate; to assess", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "purgar", meaning: "to purge, purify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "quebrar", meaning: "to break, smash; to interrupt", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "quejarse", meaning: "to complain, protest", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "querer", meaning: "to want; to love", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "rascar", meaning: "to scrape, rasp, scratch", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "rasgar", meaning: "to tear", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ratificar", meaning: "to ratify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "realizar", meaning: "to make real, realize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "reaparecer", meaning: "to reappear, return", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "recalentar", meaning: "to reheat, overheat", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "recargar", meaning: "to overload; to increase tax", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "rechazar", meaning: "to repel, reject", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "recoger", meaning: "to gather, pick up", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "recomendar", meaning: "to recommend", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "recomenzar", meaning: "to begin again, recommence", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "recomponer", meaning: "to mend, repair; (inf) to dress up", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "reconocer", meaning: "to recognize, identify, acknowledge", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "reconstituir", meaning: "to reconstitute", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "reconstruir", meaning: "to rebuild", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "recontar", meaning: "to recount, count again; retell", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "reconvenir", meaning: "to reprimand", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "recordar", meaning: "to remember, remind", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "rectificar", meaning: "to rectify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "recubrir", meaning: "to cover, coat", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "reducir", meaning: "to reduce", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "reelegir", meaning: "to re-elect", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "referir", meaning: "to tell, refer", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "regar", meaning: "to water, irrigate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "regir", meaning: "to rule, govern, prevail", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "rehacer", meaning: "to redo", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "reír", meaning: "to laugh", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "releer", meaning: "to reread", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "remarcar", meaning: "to observe, remark; to emphasize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "remorder", meaning: "to grieve", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "remover", meaning: "to remove; to dig/stir up", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "renacer", meaning: "to be reborn; to revive", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "rendir", meaning: "to produce, yield; to defeat; to exhaust", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "reñir", meaning: "to quarrel; to scold", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "renovar", meaning: "to renovate, renew", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "reorganizar", meaning: "to reorganize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "repentizar", meaning: "to ad-lib, to improve, to sight-read", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "repetir", meaning: "to repeat", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "replicar", meaning: "to retort, rejoin, answer back", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "reponer", meaning: "to replace", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "reproducir", meaning: "to reproduce", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "requerir", meaning: "to require; to request", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "resentirse", meaning: "to resent; to suffer from", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "resfriar", meaning: "to cool", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "resolver", meaning: "to solve, resolve", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "restituir", meaning: "to return, give back; to restore", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "resurgir", meaning: "to reappear; to recover", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "retener", meaning: "to retain, hold back", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "retorcer", meaning: "to twist", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "retraer", meaning: "to bring back; to dissuade", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "reventar", meaning: "to burst, explode, pop", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "revertir", meaning: "to revert", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "revocar", meaning: "to revoke; to dissuade", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "revolver", meaning: "to stir through, disturb", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "rezar", meaning: "to pray, read, say", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ridiculizar", meaning: "to ridicule", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "rizar", meaning: "to curl, ripple", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "rociar", meaning: "to spray, douse, sprinkle", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "rodar", meaning: "to roll, wheel; to travel; to race", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "rogar", meaning: "to plead, beg, pray", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "romper", meaning: "to break, tear", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "roncar", meaning: "to snore; to threaten", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "rozar", meaning: "to rub, chafe; to border on", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "saber (to know; to find out)", meaning: "verb tables", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "sacar", meaning: "to take out; to produce, make", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "salir", meaning: "to leave, go out", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "salpicar", meaning: "to sprinkle, splash, scatter", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "santiguar", meaning: "to bless, make the sign of the cross", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "satirizar", meaning: "to satirize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "satisfacer", meaning: "to satisfy", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "secar", meaning: "to dry; to annoy, bore", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "seducir", meaning: "to seduce, charm; to bribe", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "segar", meaning: "to harvest", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "segregar", meaning: "to segregate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "seguir", meaning: "to follow, continue; to chase", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "sembrar", meaning: "to sow, spread", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "sensibilizar", meaning: "to sensitize, make aware", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "sentar", meaning: "to sit, place; to suit, fit", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "sentir", meaning: "to feel, sense; to regret", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ser (to be)", meaning: "verb tables", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "serrar", meaning: "to saw", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "servir", meaning: "to serve", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "significar", meaning: "to mean, signify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "simbolizar", meaning: "to symbolize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "simpatizar", meaning: "to get along", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "simplificar", meaning: "simplify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "situar", meaning: "to put, place; to locate; to invest", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "sobrecoger", meaning: "to startle, scare", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "sobreponer", meaning: "to superimpose; to favor", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "socializar", meaning: "to socialize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "sofocar", meaning: "to suffocate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "soler", meaning: "to be used to", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "solidificar", meaning: "to solidify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "sollozar", meaning: "to sob", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "soltar", meaning: "to release", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "sonar", meaning: "to sound, ring", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "soñar", meaning: "to dream", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "sonreír", meaning: "to smile", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "sostener", meaning: "to support, maintain, sustain", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "subvenir", meaning: "to meet, defray", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "subvertir", meaning: "to subvert, undermine", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "subyugar", meaning: "subjugate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "sugerir", meaning: "to suggest", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "sumergir", meaning: "to immerse, submerge", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "superponer", meaning: "to superimpose", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "suplicar", meaning: "to beg, implore", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "suponer", meaning: "to suppose, assume", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "surgir", meaning: "to emerge, surge", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "sustituir", meaning: "to substitute", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "sustraer", meaning: "to subtract, deduct", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "temblar", meaning: "to tremble", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "tender", meaning: "to extend, stretch; to tend (to)", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "tener (to have)", meaning: "verb tables", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "teñir", meaning: "to dye", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "tentar", meaning: "to try, to tempt, to touch", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "teorizar", meaning: "to theorize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "testificar", meaning: "to attest, testify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "tipificar", meaning: "to typify, characterize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "tocar", meaning: "to touch, play an instrument", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "torcer", meaning: "to twist; to influence", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "tostar", meaning: "to toast, tan", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "traducir", meaning: "to translate; to express", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "traer", meaning: "to bring", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "traficar", meaning: "to traffic, trade, deal in", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "tragar", meaning: "to swallow", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "tranquilizar", meaning: "to calm, reassure", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "transferir", meaning: "to transfer; to postpone", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "transponer", meaning: "to transpose; to transplant", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "trazar", meaning: "to draw, trace", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "trenzar", meaning: "to braid, plait", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "tropezar", meaning: "to stumble; to run into someone", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ufanarse", meaning: "to boast", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "unificar", meaning: "to unify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "utilizar", meaning: "to use, utilize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "vacar", meaning: "to become vacant; to idle; to devote o.s. to; to lack", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "vaciar", meaning: "to empty", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "vagar", meaning: "to wander, prowl, loiter", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "valer", meaning: "to cost, be worth", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "valorizar", meaning: "to value, appraise", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "vaporizar", meaning: "to vaporize", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "variar", meaning: "to vary", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "vencer", meaning: "to defeat, overcome; to win", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "vengar", meaning: "to avenge", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "venir (to come; to happen)", meaning: "verb tables", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "ver (to see)", meaning: "verb tables", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "verificar", meaning: "to verify", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "versificar", meaning: "to versify, put into verse", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "verter", meaning: "to pour", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "vestir", meaning: "to dress, wear", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "vindicar", meaning: "to avenge, vindicate", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "visualizar", meaning: "to visualize; to display", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "vocalizar", meaning: "to vocalize; to hum", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "volar", meaning: "to fly; to blow up", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "volver", meaning: "to return; to turn over/around", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "vulgarizar", meaning: "to popularize, spread knowledge of", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "yuxtaponer", meaning: "to juxtapose", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },
    { voc: "zurcir", meaning: "to darn, mend", tag: ALL_MAIN_TENSES, personal: DEFAULT_PERSONAL, personalImperative: DEFAULT_IMPERATIVE_PERSONAL, regular: false },];
// 標題列
console.log("voc\tmeaning\tending\tcategory");
// 資料列
verbs.forEach(v => {
    const ending = v.voc.slice(-2);
    const category = `${ending.toUpperCase()} 動詞`;
    // 用 \t (Tab) 將欄位串接起來
    console.log(`${v.voc}%${v.meaning}%${ending}%${category}`);
});
